apiVersion: v1
kind: Service
metadata:
  name: mcg-demo
  namespace: mcg-demo
spec:
  selector:
    app: mcg-demo
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: mcg-demo
  namespace: mcg-demo
